# Generated by Django 3.2 on 2021-05-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to=None)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name': 'Crop', 'verbose_name_plural': 'Crops'},
        ),
        migrations.AlterModelOptions(
            name='fertilizer',
            options={'verbose_name': 'Fertilizer', 'verbose_name_plural': 'Fertilizers'},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name': 'Query', 'verbose_name_plural': 'Queries'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='seed',
            options={'verbose_name': 'Seed', 'verbose_name_plural': 'Seeds'},
        ),
        migrations.AlterModelOptions(
            name='soil',
            options={'verbose_name': 'Soil', 'verbose_name_plural': 'Soils'},
        ),
        migrations.AlterModelOptions(
            name='trainingregistration',
            options={'verbose_name': 'Training Registration', 'verbose_name_plural': 'Training Registrations'},
        ),
        migrations.RemoveField(
            model_name='crop',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='seed',
        ),
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='harvest',
            field=models.CharField(default='March - April', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='img',
            field=models.ImageField(default='crop.jpg', upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='sown',
            field=models.CharField(default='March - April', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='type',
            field=models.CharField(default='Food Crop', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='madeof',
            field=models.CharField(default='No idea', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='harvest',
            field=models.CharField(default='June - July', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='sown',
            field=models.CharField(default='Sepetmber - October', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='seed',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='soil',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
