# Generated by Django 3.2 on 2021-05-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210531_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seed',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='soil',
            name='description',
            field=models.TextField(),
        ),
    ]
