# Generated by Django 3.2 on 2021-05-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210531_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='type_of',
            field=models.CharField(default='Inorganic Fertilizer', max_length=50),
            preserve_default=False,
        ),
    ]
