# Generated by Django 3.2 on 2021-05-31 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_fertilizer_type_of'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'purchase', 'verbose_name_plural': 'purchases'},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='img',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='rate',
        ),
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.TextField(default='no addr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='city',
            field=models.CharField(default='lucknow', max_length=32),
        ),
        migrations.AddField(
            model_name='purchase',
            name='country',
            field=models.CharField(default='india', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='instructions',
            field=models.TextField(default='no instructions'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pincode',
            field=models.CharField(default='226001', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_details',
            field=models.TextField(default='no details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_amt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
