# Generated by Django 3.2 on 2021-05-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_seed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='img',
            field=models.ImageField(upload_to='seeds'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='img',
            field=models.ImageField(upload_to='None'),
        ),
    ]
