# Generated by Django 3.2 on 2021-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210531_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='img',
            field=models.ImageField(upload_to='crops'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='img',
            field=models.ImageField(upload_to='fertilzers'),
        ),
        migrations.AlterField(
            model_name='season',
            name='img',
            field=models.ImageField(upload_to='seasons'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='img',
            field=models.ImageField(upload_to='soils'),
        ),
    ]
