# Generated by Django 3.2 on 2021-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210531_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addseed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(default='lucknow', max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('pincode', models.CharField(max_length=6)),
                ('price', models.FloatField(default=25.0)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('total_amt', models.FloatField(default=0.0)),
                ('product_detail', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='addseeds')),
            ],
            options={
                'verbose_name': 'addseed',
                'verbose_name_plural': 'addseeds',
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='instructions',
        ),
        migrations.AddField(
            model_name='contact',
            name='occupation',
            field=models.CharField(default='Farmer', max_length=50),
            preserve_default=False,
        ),
    ]
