# Generated by Django 3.2 on 2021-06-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210602_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addseed',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addseed',
            name='city',
        ),
        migrations.RemoveField(
            model_name='addseed',
            name='country',
        ),
        migrations.RemoveField(
            model_name='addseed',
            name='pincode',
        ),
    ]
