# Generated by Django 3.2 on 2021-06-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210603_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment',
            field=models.CharField(default='COD', max_length=50),
        ),
    ]
