# Generated by Django 3.2 on 2021-06-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_purchase_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('card', 'Credit card')], default='cod', max_length=5),
        ),
    ]
