# Generated by Django 3.2 on 2021-06-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_purchase_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='payment',
        ),
    ]
