# Generated by Django 3.2 on 2021-06-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_purchase_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingregistration',
            name='email',
            field=models.EmailField(default='nehasingh199947@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='query',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='query',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trainingregistration',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
