# Generated by Django 3.2 on 2021-06-17 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be of 10 digits.', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='profile')),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.AddField(
            model_name='addseed',
            name='address',
            field=models.CharField(default='no address specified', max_length=500),
        ),
        migrations.AddField(
            model_name='addseed',
            name='mobile',
            field=models.CharField(default=7388308967, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be of 10 digits.', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
