# Generated by Django 3.2 on 2021-06-18 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_auto_20210617_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date',
            new_name='updated_on',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='Full_Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('O', 'Others'), ('M', 'Male')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addseed',
            name='address',
            field=models.CharField(default='No address specified', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(upload_to='users'),
        ),
    ]
