# Generated by Django 3.2 on 2021-06-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210618_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('O', 'Others'), ('F', 'Female')], default='', max_length=6),
        ),
    ]
