# Generated by Django 3.2 on 2021-06-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210619_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('O', 'Others'), ('M', 'Male'), ('F', 'Female')], default='', max_length=6),
        ),
    ]
