# Generated by Django 3.1.4 on 2021-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210623_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('O', 'Others'), ('F', 'Female'), ('M', 'Male')], default='', max_length=6),
        ),
    ]
